spring:
    datasource:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:tcp://localhost/~/test
          username: sa
          password:
#          data: classpath:config/sql/init.sql
#    batch:
#      initialize-schema: always
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
server:
    port: 9999